# help with multiple branches and config files: https://www.appveyor.com/blog/2014/07/23/appveyor-yml-and-multiple-branches/
environment:
  releaseVersion: '3.0.0'
version: '$(releaseVersion).{build}'
configuration: Release
skip_tags: true
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(releaseVersion).{build}'
  assembly_file_version: '$(releaseVersion).{build}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore src/Scrambles.sln
