// <auto-generated />
namespace Data.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VideoUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VideoUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201610081722175_VideoUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
